import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Test Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
    </>
  );
}
